"""
Notion Export Service — export charts and analysis results to Notion.

Two modes:
  1. Direct mode — if NOTION_API_KEY is set, creates Notion pages via the API.
  2. MCP-ready mode — saves structured exports as JSON for push via Notion MCP.

Both modes save a local record in working/notion_exports/.
"""
from __future__ import annotations

import json
import logging
import os
import uuid
from datetime import datetime
from pathlib import Path

from dotenv import load_dotenv

from web.config import BASE_DIR, CHART_OUTPUT_DIR

logger = logging.getLogger(__name__)

EXPORTS_DIR = BASE_DIR / "working" / "notion_exports"
EXPORTS_DIR.mkdir(parents=True, exist_ok=True)

# Reload .env on import so keys are available
load_dotenv(str(BASE_DIR / ".env"), override=True)


# ---------------------------------------------------------------------------
# Notion API helpers (direct mode — requires NOTION_API_KEY)
# ---------------------------------------------------------------------------

def _get_notion_client():
    """Return an authenticated Notion client, or None if not configured."""
    api_key = os.environ.get("NOTION_API_KEY", "").strip()
    if not api_key:
        return None
    try:
        from notion_client import Client
        return Client(auth=api_key)
    except Exception as exc:
        logger.warning("Failed to create Notion client: %s", exc)
        return None


def _get_parent_page_id() -> str | None:
    """Return the configured Notion parent page ID."""
    return os.environ.get("NOTION_PARENT_PAGE_ID", "").strip() or None


def _notion_text_block(text: str, block_type: str = "paragraph") -> dict:
    segments = []
    for i in range(0, len(text), 2000):
        segments.append({"type": "text", "text": {"content": text[i:i + 2000]}})
    return {"object": "block", "type": block_type, block_type: {"rich_text": segments}}


def _notion_heading(text: str, level: int = 2) -> dict:
    block_type = f"heading_{min(max(level, 1), 3)}"
    return {
        "object": "block", "type": block_type,
        block_type: {"rich_text": [{"type": "text", "text": {"content": text[:2000]}}]},
    }


def _notion_code(code: str, language: str = "sql") -> dict:
    segments = []
    for i in range(0, len(code), 2000):
        segments.append({"type": "text", "text": {"content": code[i:i + 2000]}})
    return {"object": "block", "type": "code", "code": {"rich_text": segments, "language": language}}


def _notion_bullet(text: str) -> dict:
    return {
        "object": "block", "type": "bulleted_list_item",
        "bulleted_list_item": {"rich_text": [{"type": "text", "text": {"content": text[:2000]}}]},
    }


def _notion_divider() -> dict:
    return {"object": "block", "type": "divider", "divider": {}}


def _create_notion_page_direct(title: str, children: list[dict]) -> dict:
    """Create a Notion page via the SDK. Returns {ok, page_url} or {ok, message}."""
    client = _get_notion_client()
    if not client:
        return {"ok": False, "message": "no_api_key"}

    parent_id = _get_parent_page_id()
    if not parent_id:
        return {"ok": False, "message": "no_parent_page"}

    try:
        page = client.pages.create(
            parent={"page_id": parent_id},
            properties={"title": [{"text": {"content": title}}]},
            children=children[:100],
        )
        page_id = page["id"]
        remaining = children[100:]
        while remaining:
            batch, remaining = remaining[:100], remaining[100:]
            client.blocks.children.append(block_id=page_id, children=batch)
        return {"ok": True, "page_id": page_id, "page_url": page.get("url", "")}
    except Exception as exc:
        logger.error("Notion API error: %s", exc)
        return {"ok": False, "message": f"Notion API error: {exc}"}


# ---------------------------------------------------------------------------
# MCP-ready content builder (Notion Markdown format)
# ---------------------------------------------------------------------------

def _build_notion_markdown(question: str, findings: list[dict], charts: list[dict], sql_queries: list[str]) -> str:
    """Build Notion-flavored Markdown content for MCP-based page creation."""
    lines = [
        f"*Generated by Siftory on {datetime.now().strftime('%Y-%m-%d %H:%M')}*",
        "",
        "---",
        "",
    ]

    if findings:
        lines.append("## Key Findings")
        lines.append("")
        for f in findings:
            text = f.get("content") or f.get("text") or str(f)
            lines.append(f"- {text}")
        lines.append("")
        lines.append("---")
        lines.append("")

    if charts:
        lines.append("## Charts")
        lines.append("")
        for c in charts:
            lines.append(f"📊 **{c.get('title', 'Chart')}**")
            lines.append("")

    if sql_queries:
        lines.append("## SQL Queries")
        lines.append("")
        for sql in sql_queries:
            lines.append("```sql")
            lines.append(sql)
            lines.append("```")
            lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("*— Exported from Siftory*")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def export_chart(
    chart_filename: str, title: str, caption: str = "", sql: str = "",
) -> dict:
    """Export a single chart to Notion."""
    export_id = uuid.uuid4().hex[:8]
    chart_path = CHART_OUTPUT_DIR / chart_filename

    if not chart_path.exists():
        return {"ok": False, "message": f"Chart file not found: {chart_filename}"}

    # Try direct mode first
    children = [_notion_heading(title, 2)]
    if caption:
        children.append(_notion_text_block(caption))
    if sql:
        children.append(_notion_code(sql))
    children.append(_notion_text_block(f"Exported from Siftory on {datetime.now().strftime('%Y-%m-%d %H:%M')}"))

    direct = _create_notion_page_direct(title, children)

    export = {
        "id": export_id, "type": "chart", "title": title, "caption": caption,
        "sql": sql, "chart_filename": chart_filename, "chart_path": str(chart_path),
        "created_at": datetime.now().isoformat(),
        "status": "exported" if direct["ok"] else "pending_mcp",
        "notion_url": direct.get("page_url", ""),
    }
    (EXPORTS_DIR / f"{export_id}.json").write_text(json.dumps(export, indent=2))

    if direct["ok"]:
        return {"ok": True, "export_id": export_id, "message": f"Chart '{title}' exported to Notion", "notion_url": direct["page_url"]}

    # MCP-ready fallback — saved for push via MCP
    return {
        "ok": True, "export_id": export_id,
        "message": "Export saved — ready for Notion push via MCP",
        "mode": "mcp_ready",
    }


def export_analysis(
    question: str, findings: list[dict], charts: list[dict], sql_queries: list[str],
) -> dict:
    """Export a full analysis to Notion."""
    export_id = uuid.uuid4().hex[:8]
    page_title = f"Analysis: {question[:80]}"

    # Build Notion API blocks for direct mode
    children = [
        _notion_text_block(f"Generated by Siftory on {datetime.now().strftime('%Y-%m-%d %H:%M')}"),
        _notion_divider(),
    ]
    if findings:
        children.append(_notion_heading("Key Findings", 2))
        for f in findings:
            text = f.get("content") or f.get("text") or str(f)
            children.append(_notion_bullet(text))
        children.append(_notion_divider())
    if charts:
        children.append(_notion_heading("Charts", 2))
        for c in charts:
            children.append(_notion_text_block(f"📊 {c.get('title', 'Chart')}"))
    if sql_queries:
        children.append(_notion_heading("SQL Queries", 2))
        for sql in sql_queries:
            children.append(_notion_code(sql))
    children.append(_notion_divider())
    children.append(_notion_text_block("— Exported from Siftory"))

    # Try direct mode
    direct = _create_notion_page_direct(page_title, children)

    # Build MCP-ready content regardless
    mcp_markdown = _build_notion_markdown(question, findings, charts, sql_queries)

    export = {
        "id": export_id, "type": "analysis", "question": question,
        "page_title": page_title,
        "findings": findings, "charts": charts, "sql_queries": sql_queries,
        "mcp_markdown": mcp_markdown,
        "created_at": datetime.now().isoformat(),
        "status": "exported" if direct["ok"] else "pending_mcp",
        "notion_url": direct.get("page_url", ""),
    }
    (EXPORTS_DIR / f"{export_id}.json").write_text(json.dumps(export, indent=2))

    if direct["ok"]:
        return {
            "ok": True, "export_id": export_id,
            "message": "Analysis exported to Notion!",
            "notion_url": direct["page_url"],
        }

    # MCP-ready fallback
    return {
        "ok": True, "export_id": export_id,
        "message": "Export saved — ready for Notion push via MCP",
        "mode": "mcp_ready",
    }


def get_pending_exports() -> list[dict]:
    """Return exports with status 'pending_mcp' that haven't been pushed yet."""
    pending = []
    for f in sorted(EXPORTS_DIR.glob("*.json"), reverse=True):
        try:
            data = json.loads(f.read_text())
            if data.get("status") == "pending_mcp":
                pending.append(data)
        except Exception:
            continue
    return pending


def mark_exported(export_id: str, notion_url: str) -> bool:
    """Mark a pending export as exported after MCP push."""
    export_file = EXPORTS_DIR / f"{export_id}.json"
    if not export_file.exists():
        return False
    try:
        data = json.loads(export_file.read_text())
        data["status"] = "exported"
        data["notion_url"] = notion_url
        data["exported_at"] = datetime.now().isoformat()
        export_file.write_text(json.dumps(data, indent=2))
        return True
    except Exception:
        return False


def list_exports() -> list[dict]:
    """List all saved exports."""
    exports = []
    for f in sorted(EXPORTS_DIR.glob("*.json"), reverse=True):
        try:
            exports.append(json.loads(f.read_text()))
        except Exception:
            continue
    return exports
